### ISSUE TITLE
Data conversion warning

### ISSUE THREAD

**Issue by greenozon** [merces/hem-hashes#4]
seen during compilation:

>hem-hashes-main\Hashes\HiewModule.c(264,47): warning C4244: '=': conversion from 'HEM_QWORD' to 'HEM_UINT', possible loss of data

**Comment by merces** [comment]
Yeah, that's because selected blocks can't be bigger than `UINT_MAX`, which is unlikely to happen but I should abort in this case anyway. Will fix in the next release, thanks!
