### ISSUE TITLE
SendTextToClipboard() note

### ISSUE THREAD

**Issue by greenozon** [merces/hem-hashes#5]
it is very well designed routine that checks for result for almost all WinAPI

I'd suggest to theck the return result from [OpenClipboard()](SendTextToClipboard) as well

**Comment by greenozon** [comment]
Also CloseClipboard() should be called 2 more times in case of errors (after OpenClipboard & befoer if (!CloseClipboard()))

**Comment by merces** [comment]
Indeed, thanks! Will be fixed in the next release. ;)
