### ISSUE TITLE
question on HiewGate_MessageWaitClose()

### ISSUE THREAD

**Issue by greenozon** [merces/hem-hashes#6]
There is a 
HiewGate_MessageWaitOpen("Calculating hashes...");

but the corresponding 
HiewGate_MessageWaitClose()
is not called in 100% of the cases

is that OK with Hiew arch?

**Comment by merces** [comment]
Good catch! Will be fixed in the next release. ;)

**Comment by merces** [comment]
Fixed in v2.00. :)
