### ISSUE TITLE
Hashes v1.03 support for Windows XP

### ISSUE THREAD

**Issue by LordGarfio** [merces/hem-hashes#7]
Hello, 

Hashes works fine on Windows XP; can you let's support it ?.

file_id.diz - dated 23.01.2023
md5 sum: 38852e3ab9e65b78b8612ce880333178 *file_id.diz
![file_id_23 01 2023](https://github.com/user-attachments/assets/d15dcbc6-692e-4616-88eb-c3e36e2a9917)

Regards.

**Comment by merces** [comment]
Does your system have a `bcrypt.dll` somewhere? I've used `bcrypt.h` functions that, according to Microsoft, are [only available on Windows Vista or newer](https://learn.microsoft.com/en-us/windows/win32/api/bcrypt/nf-bcrypt-bcryptclosealgorithmprovider#remarks).

**Comment by LordGarfio** [comment]
Right, I forgot to mention the bcrypt library for Windows XP (54884554dff39911c19daae79310072d *bcrypt.dll).

https://github.com/Blaukovitch/bcrypt-XP

**Comment by merces** [comment]
Oh, this is great news. I didn't know someone had ported it to Windows XP. 😮

I'll run some tests and if everything goes well I'll add it to the release process. Many thanks! 🙌
